#!/bin/bash
#PBS -P jh00
#PBS -q normalbw
#PBS -l walltime=48:00:00,jobfs=16GB
#PBS -l mem=128GB
#PBS -l ncpus=56

source ~/cry17-jobfs.bashrc

                                                        #If you have multiple jobs running in the same folder
                                                        #make sure you change the temorary directory location

TMPFOLDER="tmp-CeO2-5"                                        #CHANGE TEMPORARY DIRECTORY NAME

JOBNAME="CeO2-5"                 #CHANGE FILENAME


                                                        #Please ignore everything below this line
                                                        ##########################################################

cd $PBS_O_WORKDIR                                       #This line allows the job to start from the bash script location (removes the need for ../../../../../short/etc...)

tmp_check () {
TMP=$1                                          #This code will create a new temporary directory if it does not exist in the folder already
        if [ -d "$TMP" ]
                then
                        echo "tmp directory exists!" >> $TMP/Backup.log
                else
                        mkdir $TMP
                        echo "tmp directory not found! New tmp directory automatically created." >> $TMP/Backup.log

        fi
}

do_copy () {                                            #This code will automatically backup your data from the JOB_FS directory into the tmp directory every hour
MAX=$1                                                  
TMP=$2

COUNTER=0
echo "$COUNTER - Job Started at $(date)" >> $TMP/Backup.log 
while [ $COUNTER -le $MAX ]; do
        if [ $COUNTER -eq $MAX ]
                        then
                                cp $PBS_JOBFS/tmp*/fort.79 $PBS_JOBFS/tmp*/HESSOPT.DAT $PBS_JOBFS/tmp*/OPTINFO.DAT $PBS_JOBFS/tmp*/fort.20 $PBS_JOBFS/tmp*/opta* $PBS_JOBFS/tmp*/optc* $PBS_JOBFS/tmp*/SCFOUT.LOG $TMP/
                                echo "$COUNTER - Backed up at $(date)" >> $TMP/Backup.log
                                sleep 3550
                                cp $PBS_JOBFS/tmp*/fort.79 $PBS_JOBFS/tmp*/HESSOPT.DAT $PBS_JOBFS/tmp*/OPTINFO.DAT $PBS_JOBFS/tmp*/fort.20 $PBS_JOBFS/tmp*/opta* $PBS_JOBFS/tmp*/optc* $PBS_JOBFS/tmp*/SCFOUT.LOG $TMP/ 
                                (( COUNTER++ ))
                                echo "$COUNTER - Final backup at $(date)" >> $TMP/Backup.log
        else
            cp $PBS_JOBFS/tmp*/fort.79 $PBS_JOBFS/tmp*/HESSOPT.DAT $PBS_JOBFS/tmp*/OPTINFO.DAT $PBS_JOBFS/tmp*/fort.20 $PBS_JOBFS/tmp*/opta* $PBS_JOBFS/tmp*/optc* $PBS_JOBFS/tmp*/SCFOUT.LOG $TMP/ &
            sleep 600
            (( COUNTER++ ))
            echo "$COUNTER - Backed up at $(date)" >> $TMP/Backup.log
        fi
done
}

MAXCOUNTER=575                                           #This is the number of hours it will back up for (-1 as the last backup cannot occur when the job is killed at the last hour)
tmp_check $TMPFOLDER                                    #Runs the tmp_check code for the directory name allocated in TMPFOLDER
do_copy $MAXCOUNTER $TMPFOLDER &                        #Runs the automatic copy code with the MAXCOUNTER and TMPFOLDER inputs

~/crystal/crystal17/utils17/runcry17-MPP.nci $JOBNAME $JOBNAME $JOBNAME $JOBNAME

kill %1                                                 #Kills the script if the job is finished/killed prematurely
